package dlms.corba;


/**
* dlms/corba/AppException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/var/java/eclipse/6231-Project/FrontEnd/src/dlms.idl
* Sunday, November 22, 2015 11:25:04 PM EST
*/

public final class AppException extends org.omg.CORBA.UserException
{

  public AppException ()
  {
    super(AppExceptionHelper.id());
  } // ctor


  public AppException (String $reason)
  {
    super(AppExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class AppException
