package dlms.corba;

/**
* dlms/corba/AppExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dlms.idl
* Sunday, December 6, 2015 12:22:15 AM EST
*/

public final class AppExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public dlms.corba.AppException value = null;

  public AppExceptionHolder ()
  {
  }

  public AppExceptionHolder (dlms.corba.AppException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dlms.corba.AppExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dlms.corba.AppExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dlms.corba.AppExceptionHelper.type ();
  }

}
