package dlms.corba;


/**
* dlms/corba/AppException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dlms.idl
* Sunday, November 29, 2015 5:56:39 PM EST
*/

public final class AppException extends org.omg.CORBA.UserException
{

  public AppException ()
  {
    super(AppExceptionHelper.id());
  } // ctor


  public AppException (String $reason)
  {
    super(AppExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class AppException
