package dlms.corba;


/**
* dlms/corba/FrontEnd.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dlms.idl
* Wednesday, December 2, 2015 11:17:34 PM EST
*/

public interface FrontEnd extends FrontEndOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FrontEnd
