package dlms.corba;


/**
* dlms/corba/FrontEndOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dlms.idl
* Sunday, November 29, 2015 5:56:39 PM EST
*/

public interface FrontEndOperations 
{
  boolean delayPayment (String bankId, int loanId, String currentDueDate, String newDueDate) throws dlms.corba.AppException;
  String printCustomerInfo (String bankId);
  int transferLoan (String bankId, int loanId, String currentBankId, String otherBankId) throws dlms.corba.AppException;
  int openAccount (String bankId, String firstName, String lastName, String emailAddress, String phoneNumber, String password) throws dlms.corba.AppException;
  int getLoan (String bankId, int accountNbr, String password, int loanAmount) throws dlms.corba.AppException;
} // interface FrontEndOperations
