package dlms.corba;

/**
* dlms/corba/FrontEndHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dlms.idl
* Wednesday, December 2, 2015 11:17:34 PM EST
*/

public final class FrontEndHolder implements org.omg.CORBA.portable.Streamable
{
  public dlms.corba.FrontEnd value = null;

  public FrontEndHolder ()
  {
  }

  public FrontEndHolder (dlms.corba.FrontEnd initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dlms.corba.FrontEndHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dlms.corba.FrontEndHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dlms.corba.FrontEndHelper.type ();
  }

}
