package dlms.corba;


/**
* dlms/corba/FrontEnd.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dlms.idl
* Sunday, December 6, 2015 12:22:16 AM EST
*/

public interface FrontEnd extends FrontEndOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FrontEnd
